### ISSUE TITLE
Warnings during compilation on m1

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/carl-storm#12] opened 2023-06-27 12:59 UTC
On m1, i get the following warnings for every object.

```
clang: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
```

**Comment by volkm** [comment] 2024-06-03 12:45
Duplicate of #33

**Closed by volkm** 2024-06-03 12:45 UTC
Labels: duplicate
